version: '3.8'
services:
  frontend:
    image: nginx:1.19
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
    ports:
      - "8080:80"
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
