version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
  message_broker:
    build:
      context: ./message_broker
      target: build
    volumes:
      - ./message_broker:/go/app
    command: air -c .air.toml
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "8081:8081"
    tty: true
    depends_on:
      - redis
  api_gateway:
    build:
      context: ./api_gateway
      target: build
    volumes:
      - ./api_gateway:/go/app
    command: air -c .air.toml
    environment:
      - API_GATEWAY_HOST=:8888
      - MESSAGE_BROKER_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_DATABASE
    ports:
      - "8888:8888"
    tty: true
    depends_on:
      - message_broker
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./api_gateway/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
