version: '3.8'
services:
  frontend:
    image: nginx:1.19
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
    ports:
      - "8080:80"
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
  message_broker:
    build:
      context: ./message_broker
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "8081:8081"
    tty: true
    depends_on:
      - redis
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./api_gateway/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
